config/routes.rb
Meetapp::Application.routes.draw do
  resource :session, :only => [:new, :create, :destroy]
  resources :meetings do
  	resources :comments, :only => [:index, :show, :create, :update]
  end
  resources :users do
  	resources :meetings, :only => [:index]
  	resources :comments, :only => [:index]
  end
  resources :groups do
  	resources :meetings, :only => [:index]
  	resources :comments, :only => [:index, :create, :update]
  end

  resource :mockup, :only => [] do 
    get "root/index", to: "mockups#root_index"
    get "user/show", to: "mockups#user_show"
    get "user/new", to: "mockups#user_new"
    get "group/show", to: "mockups#group_show"
    get "group/meeting", to: "mockups#group_meeting"
    get "group/members", to: "mockups#group_members"
    get "meeting/show", to: "mockups#meeting_show"
  end

  root to: "users#index"
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :name, :description, :location, :start_date,
  	:start_time, :end_date, :end_time, :time_zone, :suggested_donation,
  	:is_past, :is_private, :additional_instructions

  after_find :check_if_past

	validates_presence_of :organizer_id, :name, :description, :location,
		:start_date, :start_time, :time_zone
	validates_length_of :name, :maximum => 50
	validates_length_of :description, :maximum => 500
	validates_length_of :location, :additional_instructions, :maximum => 200

	belongs_to :organizer,
						:class_name => "User",
						:primary_key => :id,
						:foreign_key => :organizer_id 
	has_many :comments, :as => :commentable
	has_many :meeting_guests,
					:class_name => "MeetingGuest",
					:primary_key => :id,
					:foreign_key => :meeting_id
	has_many :guests, :through => :meeting_guests, :source => :user

	def self.organized_by(organizer_id)
		self.where(:organizer_id => organizer_id)
	end

	def self.hosted_by(group_id)
		self.where(:group_ird => group_id)
	end

	private

	def check_if_past
		unless self.is_past
			#only compares dates, not times within a date
			current_date = Time.now.strftime("%F").to_time
			starting_date = self.start_date.strftime("%F").to_time

			if starting_date < current_date
				self.is_past = true
			end
		end
	end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

	def index
		if params[:user_id]
			@meetings = Meeting.organized_by(params[:user_id])
			# .includes(organizer) ?
			# @source = User.find(params[:user_id])
		elsif params[:group_id]
			@meetings = Meeting.hosted_by(params[:group_id])
			# .includes(organizer) ?
			# @source = Group.find(params[:group_id])
		else
			@meetings = Meeting.all
			# @source = nil
		end
		render :index
	end

	def show

	end

	def new
		render :new
	end

	def create
		@meeting = Meeting.new(params[:meeting])

		if meeting.save
			flash[:notices] = ["Successfully created new meeting: #{@meeting.name}"]
			redirect_to meeting_url(@meeting)
		else
			flash.now[:notices] = @meeting.errors.full_messages
			render :new
		end
	end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_meeting_form.html.haml
- put ||= false
- if meeting.nil?
	- name = ""
	- description = ""
	- start_date = ""
	- start_time = ""
	- end_date = ""
	- end_time = ""
	- time_zone = "Pacific Time (US & Canada)"
	- location = ""
	- additional_instructions = ""
	- suggested_donation = ""
	- is_private = false
- else
	- name = meeting.name || ""
	- description = meeting.description || ""
	- start_date = meeting.start_date || ""
	- start_time = meeting.start_time || ""
	- end_date = meeting.end_date || ""
	- end_time = meeting.end_time || ""
	- location = meeting.location || ""
	- additional_instructions = meeting.additional_instructions || ""
	- suggested_donation = meeting.suggested_donation || ""

%form{:action => action, :method => "POST", :data => {:abide => true}}
	%input{:type => "hidden", :name => "authenticity_token", :value => form_authenticity_token}

	- if put
		%input{:type => "hidden", :name => "_method", :value => "PUT"}

	.row
		.small-12.column.meeting-name-field
			%label
				Meeting name
				%small Required, maximum 50 characters
				%input{:type => "text", :name => "meeting[name]", :value => name, :required => true}
				%small.error Name is required

	.row
		.small-12.column.meeting-description-field
			%label
				Description
				%small Required, maximum 500 characters
				%textarea{:name => "meeting[description]", :value => description, :placeholder => "What's this meeting about?", :required => true, :rows => 4}
				%small.error Description is required

	.row
		.small-6.columns
			Start
		.small-6.columns
			End
		.small-4.columns.meeting-start-date-field
			%label
				Date
				%small Required
				%input.date-input#meeting-start-date{:type => "date", :name => "meeting[start_date]", :value => start_date, :required => true, :pattern => "date"}
				%small.error Start date is required

		.small-2.columns.meeting-start-time-field
			%label
				Time
				%small Required
				%input.time-input#meeting-start-time{:type => "time", :name => "meeting[start_time]", :value => start_time, :required => true, :pattern => "^[0-2][0-9]:[0-5][0-9]$" }
				%small.error Start time is required

		.small-4.columns.meeting-end-date-field
			%label
				Date
				%input.date-input#meeting-end-date{:type => "date", :name => "meeting[end_date]", :value => start_date, :pattern => "date"}

		.small-2.columns.meeting-end-time-field
			%label
				Time
				%input.time-input#meeting-end-time{:type => "time", :name => "meeting[end_time]", :value => end_time, :pattern => "^[0-2][0-9]:[0-5][0-9]$" }


	.row
		.small-5.columns.meeting-time-zone-field
			%label
				Time Zone
				%small Required
				= time_zone_select("meeting", "time_zone", ActiveSupport::TimeZone.us_zones, {:default => time_zone, :required => true})
				%small.error Time Zone is required

		.small-3.columns.meeting-suggested-donation-field
			%label
				%span.has-tip{:title => "in dollars per person", :data => {:tooltip => true}}
					Suggested donation
				%input{:type => "number", :name => "meeting[suggested_donation]", :value => suggested_donation, :pattern => "number", :placeholder => 0}
				%small.error Invalid amount

		.small-4.columns.meeting-privacy-field
			%label
				%input#meeting-is-private{:type => "checkbox", :name => "meeting[is_private]", :checked => is_private}
				%span.has-tip{:title => "Only allows group members or people you invite to view this meeting",:data => {:tooltip => true}}
					Make meeting private?

	.row
		.small-6.columns.meeting-location-field
			%label
				Location address
				%small Required
			%textarea{:name => "meeting[location]", :placeholder => "Ex. City Hall, San Francisco, CA 94102", :required => true, :rows => 4}
				= location
			%small.error Please provide an address

		.small-6.columns.meeting-additional-instructions-field
			%label
				Additional instructions
			%textarea{:name => "meeting[additional_instructions]", :placeholder => "Ex. Enter code '1234' at the door; please bring a laptop with you", :rows => 4}
				= additional_instructions

	%input.button{:type => "submit", :value => (put ? "Update Meeting" : "Post Meeting")}

app/views/meetings/_meeting_show.html.haml
.small-8.columns
	%h1
		Name of meeting goes here
		/ meeting.name

	Links to various social networks

	%h5
		Sunday, March 16, 2014
		/ meeting.date(:full)
	%hr
	%h5
		Location Name
		%small
			1234 Street St.
			City, State
	%p 
		Additional instructions
		/ meeting.location_instructions
	%hr
	%h5
		Suggested donation: $2.00
		%small /per person
		/ meeting.suggested_donation
	%hr
	%p
		Description of meeting goes here
		/ meeting.description
	%hr

	%h5
		- if logged_in?
			= "Hey #{current_user.first_name}, leave a comment!"
			%textarea
		- else
			%a{:href => new_session_url}
				Sign in
			or
			%a{:href => new_user_url}
				Sign up
			to let your voice be heard!

.small-4.columns
	%h5 Will you attend?
	%a.button.small{:href => "#"}
		Yes
	%a.button.small{:href => "#"}
		No
	%hr
	%h5 N attending
	List of attendees goes here

	%hr
	%h5 M not attending
	Collapsible list of non-attendees

app/views/meetings/new.html.haml
.row
	.small-12.medium-8.column
		%h1 Create new meeting
		= render 'meeting_form', {:action => meetings_url, :meeting => @meeting || nil}

app/views/meetings/show.html.haml
.row
	= render 'meeting_show'