config/routes.rb
Meetapp::Application.routes.draw do
  resource :session, :only => [:new, :create, :destroy]
  resources :meetings do
  	resources :comments, :only => [:index, :show, :create, :update]
  end
  resources :users do
  	resources :meetings, :only => [:index]
  	resources :comments, :only => [:index]
  end
  resources :groups do
  	resources :meetings, :only => [:index]
  	resources :comments, :only => [:index, :create, :update]
  end

  resource :mockup, :only => [] do 
    get "root/index", to: "mockups#root_index"
    get "user/show", to: "mockups#user_show"
    get "user/new", to: "mockups#user_new"
    get "group/show", to: "mockups#group_show"
    get "group/meeting", to: "mockups#group_meeting"
    get "group/members", to: "mockups#group_members"
    get "meeting/show", to: "mockups#meeting_show"
  end

  root to: "users#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meetapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div>
		<%= link_to "Users", users_url %>
		<%= link_to "Groups", groups_url %>
		|
		<% if logged_in? %>
			Logged in as 
			<%= link_to "#{current_user.username}", user_url(current_user) %>
			<%= link_to "Log out", session_url, :method => :delete %>
		<% else %>
			Welcome, guest.
			<%= link_to "Log in", new_session_url %>
			or
			<%= link_to "Sign up", new_user_url %>
		<% end %>
	</div>

	<% unless flash[:notices].nil? %>
		<div style="border: 1px solid black; background-color: khaki;">
			<ul>
			<% flash[:notices].each do |notice| %>
				<li><%= notice %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title Meetapp

		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags

	%body
		.contain-to-grid
			%nav{:class => "top-bar", :data => {:topbar => true}}
				%ul.title-area
					%li.name
						%h1
							%a{:href => "/"}
								Meetapp

				%section.top-bar-section
					%ul.right
						- if logged_in?
							%li.active.has-dropdown
								%a{:href => "#"}
									= link_to "#{current_user.username}", user_url(current_user)
								%ul.dropdown
									%li
										= link_to "Sign out", session_url, :method => :delete
						- else
							%li
								%a{:href => "#"}
									Welcome, Guest
							%li.divider
							%li
								= link_to "Sign in", new_session_url
							%li
								= link_to "Sign up", new_user_url

					%ul.left
						%li
							= link_to "Users", users_url
						%li
							= link_to "Groups", groups_url
						%li.has-dropdown
							%a{:href => "#"}
								Mockups
							%ul.dropdown
								%li
									= link_to "Root index", root_index_mockup_url
								%li
									= link_to "User show", user_show_mockup_url

		- unless flash[:notices].nil?
			.row
				%br
				.small-12.medium-8.medium-offset-1.alert-box.radius{:data => {alert: true}}
					- flash[:notices].each do |notice|
						= notice
						%br
					%a.close{:href => "#"}
						&times;

	.row
		= yield

app/views/layouts/application_original.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meetapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div>
		<%= link_to "Users", users_url %>
		<%= link_to "Groups", groups_url %>
		|
		<% if logged_in? %>
			Logged in as 
			<%= link_to "#{current_user.username}", user_url(current_user) %>
			<%= link_to "Log out", session_url, :method => :delete %>
		<% else %>
			Welcome, guest.
			<%= link_to "Log in", new_session_url %>
			or
			<%= link_to "Sign up", new_user_url %>
		<% end %>
	</div>

	<% unless flash[:notices].nil? %>
		<div style="border: 1px solid black; background-color: khaki;">
			<ul>
			<% flash[:notices].each do |notice| %>
				<li><%= notice %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

<%= yield %>

</body>
</html>